# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes_item',
            name='clothing_type',
            field=models.CharField(choices=[(' ', ' ')], max_length=14),
        ),
    ]
