# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20161107_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes_item',
            name='brand',
            field=models.CharField(default='N/A', max_length=32),
        ),
        migrations.AddField(
            model_name='clothes_item',
            name='color',
            field=models.CharField(default='N/A', max_length=32),
        ),
        migrations.AlterField(
            model_name='clothes_item',
            name='clothing_type',
            field=models.CharField(choices=[('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Dresses', 'Dresses'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Costumes', 'Costumes'), ('Other', 'Other')], max_length=14),
        ),
    ]
