# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20161114_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes_item',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='media/clothes_images/'),
        ),
    ]
